[tool.poetry]
name = "py2exe-gui"
version = "0.1.0"
description = "基于PySide6的PyInstaller图形界面工具"
keywords = ["PyInstaller", "GUI", "PySide6"]
authors = ["muzing <muzi2001@foxmail.com>"]
license = "GPL-3.0-or-later"
readme = "README.md"
repository = "https://github.com/muziing/Py2exe-GUI"

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
PySide6 = "^6.3"

[tool.poetry.dev-dependencies]
black = "^22"
isort = "^5"
mypy = "^0.971"
pyinstaller = "^5.3"

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/muziing/Py2exe-GUI/issues"

[tool.black]
line-length = 88
target-version = ['py310']

[tool.isort]
profile = "black"
line_length = 88

[tool.mypy]
python_version = "3.10"
warn_return_any = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
